"""
This bot is created by Abdul Majid . https://github.com/majidabdulred .
"""

import discord
from parsedata import getimage
from fuzzywuzzy import process
import os

names = ['Griffin', 'Bantam', 'Bantam II', 'Condor', 'Merlin', 'Kestrel', 'Condor II', 'Condor Interceptor',
         'Condor II Interceptor', 'Merlin Assault', 'Manticore', 'Manticore II', 'Heron', 'Heron Covert Ops',
         'Vigil',
         'Burst', 'Burst II', 'Slasher', 'Rifter', 'Breacher', 'Slasher II', 'Breacher Assault', 'Hound', 'Probe',
         'Probe Covert Ops', 'Crucifier', 'Inquisitor', 'Inquisitor II', 'Executioner', 'Tormentor', 'Punisher',
         'Executioner II', 'Executioner Interceptor', 'Executioner II Interceptor', 'Punisher Assault', 'Purifier',
         'Purifier II', 'Magnate', 'Magnate Covert Ops', 'Maulus', 'Navitas', 'Navitas II', 'Atron', 'Tristan',
         'Incursus', 'Atron II', 'Atron II Interceptor', 'Incursus Assault', 'Nemesis', 'Nemesis II', 'Imicus',
         'Imicus Covert Ops', 'Worm', 'Dramiel', 'Cruor', 'Astero', 'Garmur', 'Succubus', 'Daredevil',
         'Cormorant Guardian', 'Cormorant', 'Corax', 'Cormorant II', 'Cormorant Navy Issue', 'Corax Assault',
         'Corax Trainer', 'Corax Sniper', 'Cormorant Covert Ops', 'Thrasher Guardian', 'Thrasher', 'Talwar',
         'Thrasher II', 'Thrasher Fleet Issue', 'Talwar Assault', 'Talwar Trainer', 'Talwar Sniper',
         'Thrasher Covert Ops', 'Coercer Guardian', 'Coercer', 'Dragoon', 'Coercer II', 'Coercer Navy Issue',
         'Dragoon Assault', 'Dragoon Trainer', 'Dragoon Sniper', 'Coercer Covert Ops', 'Catalyst Guardian',
         'Catalyst',
         'Algos', 'Catalyst II', 'Catalyst Navy Issue', 'Algos Assault', 'Algos Trainer', 'Algos Sniper',
         'Moa Guardian', 'Blackbird', 'Osprey', 'Caracal', 'Moa', 'Caracal Navy Issue', 'Caracal Trainer',
         'Moa Trainer', 'Caracal Sniper', 'Blackbird Covert Ops', 'Blackbird II Covert Ops', 'Rupture Guardian',
         'Rupture II Guardian', 'Bellicose', 'Scythe', 'Stabber', 'Stabber Fleet Issue', 'Rupture',
         'Stabber Trainer',
         'Rupture Trainer', 'Stabber Sniper', 'Bellicose Covert Ops', 'Maller Guardian', 'Maller II Guardian',
         'Arbitrator', 'Augoror', 'Omen', 'Maller', 'Omen Navy Issue', 'Omen Trainer', 'Maller Trainer',
         'Omen Sniper',
         'Arbitrator Covert Ops', 'Thorax Guardian', 'Celestis', 'Exequror', 'Vexor', 'Vexor Navy Issue', 'Thorax',
         'Vexor Trainer', 'Thorax Trainer', 'Vexor Sniper', 'Celestis Covert Ops', 'Thorax Prototype', 'Gila',
         'Cynabal', 'Ashimmu', 'Stratios', 'Orthrus', 'Phantasm', 'Vigilant', 'Ferox Guardian', 'Naga', 'Naga II',
         'Ferox', 'Drake', 'Cyclone II Guardian', 'Tornado II', 'Hurricane Logistics', 'Cyclone', 'Hurricane',
         'Hurricane Prototype', 'Prophecy Guardian', 'Prophecy II Guardian', 'Oracle', 'Oracle II',
         'Harbinger Logistics', 'Prophecy', 'Harbinger', 'Harbinger Prototype', 'Myrmidon Guardian',
         'Myrmidon II Guardian', 'Talos', 'Talos II', 'Myrmidon', 'Brutix', 'Scorpion', 'Raven Striker', 'Rokh',
         'Raven', 'Maelstrom Striker', 'Tempest', 'Armageddon', 'Apocalypse Striker', 'Apocalypse', 'Abaddon',
         'Megathron Striker', 'Dominix', 'Megathron', 'Hyperion', 'Rattlesnake', 'Machariel', 'Bhaalgorn', 'Nestor',
         'Barghest', 'Nightmare', 'Vindicator', 'Tayra', 'Badger', 'Badger II', 'Wreathe', 'Mammoth', 'Wreathe II',
         'Bestower', 'Sigil', 'Sigil II', 'Kryos', 'Nereus', 'Nereus II', 'Nereus High Mobility', 'Nereus Combat',
         'Nereus Hauling', 'Imicus High Mobility', 'Humpback High Mobility', 'Humpback Hauling', 'Humpback Combat',
         'Retriever', 'Procurer', 'Covetor', 'Venture Trainer', 'Venture', 'Venture II', 'Venture III',
         'MK1 Small Rifled Railgun', 'MK3 Small Rifled Railgun', 'MK5 Small Rifled Railgun',
         'MK7 Small Rifled Railgun',
         'MK9 Small Rifled Railgun', "'Musket' Small Rifled Railgun", 'Caldari Navy Small Rifled Railgun',
         'Federation Navy Small Rifled Railgun', 'Dread Guristas Small Rifled Railgun',
         'Shadow Serpentis Small Rifled Railgun', "'Quafe' Small Rifled Railgun",
         'Coreli C-Type Small Rifled Railgun',
         'MK5 Medium Rifled Railgun', 'MK7 Medium Rifled Railgun', 'MK9 Medium Rifled Railgun',
         "'Flintlock' Medium Rifled Railgun", 'Caldari Navy Medium Rifled Railgun',
         'Federation Navy Medium Rifled Railgun', 'Shadow Serpentis Medium Rifled Railgun',
         "'Magnate' Medium Rifled Railgun", 'Corelum C-Type Medium Rifled Railgun', 'MK7 Large Rifled Railgun',
         'MK9 Large Rifled Railgun', "'Popper' Large Rifled Railgun", 'Caldari Navy Large Rifled Railgun',
         'Federation Navy Large Rifled Railgun', "'Poison' Large Rifled Railgun ",
         'Core C-Type Large Rifled Railgun',
         'Civilian Small Snubnosed Railgun', 'MK1 Small Snubnosed Railgun', 'MK3 Small Snubnosed Railgun',
         'MK5 Small Snubnosed Railgun', 'MK7 Small Snubnosed Railgun', 'MK9 Small Snubnosed Railgun',
         "'Dealer' Small Snubnosed Railgun", 'Federation Navy Small Snubnosed Railgun',
         "'Quafe' Small Snubnosed Railgun ", 'Coreli C-Type Small Snubnosed Railgun',
         'Civilian Medium Snubnosed Railgun', 'MK5 Medium Snubnosed Railgun', 'MK7 Medium Snubnosed Railgun',
         'MK9 Medium Snubnosed Railgun', "'Hustler' Medium Snubnosed Railgun",
         'Federation Navy Medium Snubnosed Railgun', "'Magnate' Medium Snubnosed Railgun ",
         'Corelum C-Type Medium Snubnosed Railgun', 'MK7 Large Snubnosed Railgun', 'MK9 Large Snubnosed Railgun',
         "'Swindler' Large Snubnosed Railgun", 'Federation Navy Large Snubnosed Railgun',
         "'Poison' Large Snubnosed Railgun ", 'Core C-Type Large Snubnosed Railgun', 'MK1 Small Beam Laser',
         'MK3 Small Beam Laser', 'MK5 Small Beam Laser', 'MK7 Small Beam Laser', 'MK9 Small Beam Laser',
         "'Mace' Small Beam Laser", 'Imperial Navy Small Beam Laser', "'Rebel' Small Beam Laser ",
         'Centii C-Type Small Beam Laser', 'Corpii C-Type Small Beam Laser', 'MK5 Medium Beam Laser',
         'MK7 Medium Beam Laser', 'MK9 Medium Beam Laser', "'Crossbow' Medium Beam Laser",
         'Imperial Navy Medium Beam Laser', "'Ritual' Medium Beam Laser", 'Centum C-Type Medium Beam Laser',
         'Corpum C-Type Medium Beam Laser', 'MK7 Large Beam Laser', 'MK9 Large Beam Laser',
         "'Catapult' Large Beam Laser", 'Imperial Navy Large Beam Laser', 'True Sansha Large Beam Laser',
         "'Ruin' Large Beam Laser ", 'Centus C-Type Large Beam Laser', 'Corpus C-Type Large Beam Laser',
         'Civilian Small Pulse Laser', 'MK1 Small Pulse Laser', 'MK3 Small Pulse Laser', 'MK5 Small Pulse Laser',
         'MK7 Small Pulse Laser', 'MK9 Small Pulse Laser', "'Longbow' Small Pulse Laser",
         'Imperial Navy Small Pulse Laser', 'True Sansha Small Pulse Laser', 'Dark Blood Small Pulse Laser',
         "'Rebel' Small Pulse Laser", 'Centii C-Type Small Pulse Laser', 'Corpii C-Type Small Pulse Laser',
         'Civilian Medium Pulse Laser', 'MK5 Medium Pulse Laser', 'MK7 Medium Pulse Laser',
         'MK9 Medium Pulse Laser',
         "'Joust' Medium Pulse Laser", 'Imperial Navy Medium Pulse Laser', 'True Sansha Medium Pulse Laser',
         'Dark Blood Medium Pulse Laser', "'Ritual' Medium Pulse Laser ", 'Centum C-Type Medium Pulse Laser',
         'Corpum C-Type Medium Pulse Laser', 'MK7 Large Pulse Laser', 'MK9 Large Pulse Laser',
         "'Halberd' Large Pulse Laser", 'Imperial Navy Large Pulse Laser', "'Ruin' Large Pulse Laser ",
         'Centus C-Type Large Pulse Laser', 'Corpus C-Type Large Pulse Laser', 'Civilian Small Autocannon',
         'MK1 Small Autocannon', 'MK3 Small Autocannon', 'MK5 Small Autocannon', 'MK7 Small Autocannon',
         'MK9 Small Autocannon', "'Jolt' Small Autocannon", 'Republic Fleet Small Autocannon',
         'Domination Small Autocannon', "'Criminal' Small Autocannon ", 'Gistii C-Type Small Autocannon',
         'Civilian Medium Autocannon', 'MK5 Medium Autocannon', 'MK7 Medium Autocannon', 'MK9 Medium Autocannon',
         "'Jolt' Medium Autocannon", 'Republic Fleet Medium Autocannon', 'Domination Medium Autocannon',
         "'Free' Medium Autocannon ", 'Gistum C-Type Medium Autocannon', 'MK7 Large Autocannon',
         'MK9 Large Autocannon',
         "'Jolt' Large Autocannon", 'Republic Fleet Large Autocannon', "'Elder' Large Autocannon ",
         'Gist C-Type Large Autocannon', 'MK1 Small Strike Cannon', 'MK3 Small Strike Cannon',
         'MK5 Small Strike Cannon', 'MK7 Small Strike Cannon', 'MK9 Small Strike Cannon',
         "'Jolt' Small Strike Cannon",
         'Republic Fleet Small Strike Cannon', 'Domination Small Strike Cannon', "'Criminal' Small Strike Cannon ",
         'Gistii C-Type Small Strike Cannon', 'MK5 Medium Strike Cannon', 'MK7 Medium Strike Cannon',
         'MK9 Medium Strike Cannon', "'Jolt' Medium Strike Cannon", 'Republic Fleet Medium Strike Cannon',
         'Domination Medium Strike Cannon', "'Free' Medium Strike Cannon ", 'Gistum C-Type Medium Strike Cannon',
         'MK7 Large Strike Cannon', 'MK9 Large Strike Cannon', "'Jolt' Large Strike Cannon",
         'Republic Fleet Large Strike Cannon', 'Domination Large Strike Cannon', "'Elder' Large Strike Cannon ",
         'Gist C-Type Large Strike Cannon', "'The Returned' Small Jetstream Decomposer",
         'Yan-Jung Small Jetstream Decomposer', "'The Departed' Small Jetstream Decomposer",
         "'The Sacrificed' Small Jetstream Decomposer", "'Wei' C Small Jetstream Decomposer",
         "'The Returned' Medium Jetstream Decomposer", 'Yan-Jung Medium Jetstream Decomposer',
         "'The Departed' Medium Jetstream Decomposer", "'The Sacrificed' Medium Jetstream Decomposer",
         "'Cheng' C Medium Jetstream Decomposer", 'MK3 Miner', 'MK5 Miner', 'MK7 Miner', 'MK9 Miner',
         'Single Diode Miner', 'Gallente Miner', 'ORE Miner', "'Ion' Miner ", 'MK5 Strip Miner', 'MK7 Strip Miner',
         'MK9 Strip Miner', 'Single Diode Strip Miner', 'Gallente Strip Miner', 'ORE Strip Miner',
         "'Ion' Strip Miner ",
         'Civilian Small Missile Launcher', 'MK1 Small Missile Launcher', 'MK3 Small Missile Launcher',
         'MK5 Small Missile Launcher', 'MK7 Small Missile Launcher', 'MK9 Small Missile Launcher',
         "'Gallows' Small Missile Launcher", 'Caldari Navy Small Missile Launcher',
         'Republic Fleet Small Missile Launcher', 'True Sansha Small Missile Launcher',
         'Dread Guristas Small Missile Launcher', 'Domination Small Missile Launcher',
         "'Discipline' Small Missile Launcher ", 'Pithi C-Type Small Missile Launcher',
         'Civilian Medium Missile Launcher', 'MK5 Medium Missile Launcher', 'MK7 Medium Missile Launcher',
         'MK9 Medium Missile Launcher', "'Challenger' Medium Missile Launcher",
         'Caldari Navy Medium Missile Launcher',
         'Republic Fleet Medium Missile Launcher', 'True Sansha Medium Missile Launcher',
         'Dread Guristas Medium Missile Launcher', 'Domination Medium Missile Launcher',
         "'Discipline' Medium Missile Launcher ", 'Pithum C-Type Medium Missile Launcher',
         'MK7 Large Missile Launcher',
         'MK9 Large Missile Launcher', "'Gallows' Large Missile Launcher", 'Caldari Navy Large Missile Launcher',
         'Republic Fleet Large Missile Launcher', 'Domination Large Missile Launcher',
         'Hurricane Large Missile Launcher ', 'Pith C-Type Large Missile Launcher',
         'MK5 Medium Rapid Missile Launcher',
         'MK7 Medium Rapid Missile Launcher', 'MK9 Medium Rapid Missile Launcher',
         "'Challenger' Medium Rapid Missile Launcher", 'Caldari Navy Medium Rapid Missile Launcher',
         'Republic Fleet Medium Rapid Missile Launcher', 'True Sansha Medium Rapid Missile Launcher',
         'Dread Guristas Medium Rapid Missile Launcher', 'Domination Medium Rapid Missile Launcher',
         'Hurricane Medium Rapid Missile Launcher', 'Pithum C-Type Medium Rapid Missile Launcher',
         'MK7 Large Rapid Missile Launcher', 'MK9 Large Rapid Missile Launcher',
         "'Gallows' Large Rapid Missile Launcher", 'Caldari Navy Large Rapid Missile Launcher',
         'Republic Fleet Large Rapid Missile Launcher', 'True Sansha Large Rapid Missile Launcher',
         'Hurricane Large Rapid Missile Launcher ', 'Pith C-Type Large Rapid Missile Launcher',
         'MK5 Medium Torpedo Launcher', 'MK7 Medium Torpedo Launcher', 'MK9 Medium Torpedo Launcher',
         "'Challenger' Medium Torpedo Launcher", 'Caldari Navy Medium Torpedo Launcher',
         'Republic Fleet Medium Torpedo Launcher', 'Dread Guristas Medium Torpedo Launcher',
         'Domination Medium Torpedo Launcher', "'Heth' Medium Torpedo Launcher ",
         'Pithum C-Type Medium Torpedo Launcher', 'MK3 Small Torpedo Launcher', 'MK5 Small Torpedo Launcher',
         'MK7 Small Torpedo Launcher', 'MK9 Small Torpedo Launcher', "'Balefire' Small Torpedo Launcher",
         'Caldari Navy Small Torpedo Launcher', 'Republic Fleet Small Torpedo Launcher',
         'True Sansha Small Torpedo Launcher', "'Heth' Small Torpedo Launcher ",
         'Pithi C-Type Small Torpedo Launcher',
         'MK7 Large Torpedo Launcher', 'MK9 Large Torpedo Launcher', "'Barrage' Large Torpedo Launcher",
         'Caldari Navy Large Torpedo Launcher', 'Republic Fleet Large Torpedo Launcher',
         'Hurricane Large Torpedo Launcher ', 'Pith C-Type Large Torpedo Launcher', 'MK3 Small Energy Nosferatu',
         'MK5 Small Energy Nosferatu', 'MK7 Small Energy Nosferatu', 'MK9 Small Energy Nosferatu',
         "'Upir' Small Energy Nosferatu", 'Imperial Navy Small Energy Nosferatu',
         'True Sansha Small Energy Nosferatu',
         "'Vrykolakas' Small Energy Nosferatu ", 'MK5 Medium Energy Nosferatu', 'MK7 Medium Energy Nosferatu',
         'MK9 Medium Energy Nosferatu', "'Upir' Medium Energy Nosferatu ", 'Imperial Navy Medium Energy Nosferatu',
         'Dark Blood Medium Energy Nosferatu', "'Vrykolakas' Medium Energy Nosferatu ",
         'MK9 Large Energy Nosferatu',
         "'Upir' Large Energy Nosferatu ", 'Imperial Navy Large Energy Nosferatu',
         'Dark Blood Large Energy Nosferatu',
         'True Sansha Large Energy Nosferatu', "'Vrykolakas' Large Energy Nosferatu",
         'MK3 Small Energy Neutralizer',
         'MK5 Small Energy Neutralizer', 'MK7 Small Energy Neutralizer', 'MK9 Small Energy Neutralizer',
         "'Caltrop' Small Energy Neutralizer", 'Imperial Navy Small Energy Neutralizer',
         'True Sansha Small Energy Neutralizer', "'Moat' Small Energy Neutralizer ",
         'MK5 Medium Energy Neutralizer',
         'MK7 Medium Energy Neutralizer', 'MK9 Medium Energy Neutralizer', "'Caltrop' Medium Energy Neutralizer ",
         'Imperial Navy Medium Energy Neutralizer', "'Moat' Medium Energy Neutralizer ",
         'MK9 Large Energy Neutralizer',
         "'Caltrop' Large Energy Neutralizer ", 'Imperial Navy Large Energy Neutralizer',
         "'Moat' Large Energy Neutralizer", 'MK3 Small Remote Capacitor Transmitter',
         'MK5 Small Remote Capacitor Transmitter', 'MK7 Small Remote Capacitor Transmitter',
         'MK9 Small Remote Capacitor Transmitter', "'Squire' Small Remote Capacitor Transmitter",
         'Imperial Navy Small Remote Capacitor Transmitter', "'Knight' Small Remote Capacitor Transmitter ",
         'MK5 Medium Remote Capacitor Transmitter', 'MK7 Medium Remote Capacitor Transmitter',
         'MK9 Medium Remote Capacitor Transmitter', "'Squire' Medium Remote Capacitor Transmiiter ",
         'Imperial Navy Medium Remote Capacitor Transmitter', "'Chivalry' Medium Remote Capacitor Transmitter",
         'MK9 Large Remote Capacitor Transmitter', "'Squire' Large Remote Capacitor Transmitter ",
         'Imperial Navy Large Remote Capacitor Transmitter', "'Chivalry' Large Remote Capacitor Transmitter",
         'MK3 Small Remote Shield Booster', 'MK5 Small Remote Shield Booster', 'MK7 Small Remote Shield Booster',
         'MK9 Small Remote Shield Booster', "'Micro' Small Remote Shield Booster",
         'Caldari Navy Small Remote Shield Booster', "'Healer' Small Remote Shield Booster ",
         'Pithi C-Type Small Remote Shield Booster', 'Gistii C-Type Small Remote Shield Booster',
         'MK5 Medium Remote Shield Booster', 'MK7 Medium Remote Shield Booster', 'MK9 Medium Remote Shield Booster',
         "'Micro' Medium Remote Shield Booster", 'Caldari Navy Medium Remote Shield Booster',
         "'Healer' Medium Remote Shield Booster ", 'Pithum C-Type Medium Remote Shield Booster',
         'Gistum C-Type Medium Remote Shield Booster', 'MK9 Large Remote Shield Booster',
         "'Micro' Large Remote Shield Booster", 'Caldari Navy Large Remote Shield Booster',
         "'Healer' Large Remote Shield Booster ", 'Pith C-Type Large Remote Shield Booster',
         'Gist C-Type Large Remote Shield Booster', 'MK3 Small Remote Armor Repairer',
         'MK5 Small Remote Armor Repairer', 'MK7 Small Remote Armor Repairer', 'MK9 Small Remote Armor Repairer',
         "'Beatnik' Small Remote Armor Repairer", 'Imperial Navy Small Remote Armor Repairer',
         "'Tranquil' Small Remote Armor Repairer ", 'Corpii C-Type Small Remote Armor Repairer',
         'Coreli C-Type Small Remote Armor Repairer', 'MK5 Medium Remote Armor Repairer',
         'MK7 Medium Remote Armor Repairer', 'MK9 Medium Remote Armor Repairer',
         "'Beatnik' Medium Remote Armor Repairer ", 'Imperial Navy Medium Remote Armor Repairer',
         "'Tranquil' Medium Remote Armor Repairer ", 'Corpum C-Type Medium Remote Armor Repairer',
         'Corelum C-Type Medium Remote Armor Repairer', 'MK9 Large Remote Armor Repairer',
         "'Beatnik' Large Remote Armor Repairer ", 'Imperial Navy Large Remote Armor Repairer',
         "'Peace' Large Remote Armor Repairer", 'Corpus C-Type Large Remote Armor Repairer', 'MK5 Cloaking Device',
         'MK7 Cloaking Device', "'Guise' Cloaking Device", 'CONCORD Cloaking Device',
         "'Smokescreen' Cloaking Device",
         'MK5 Covert Ops Cloaking Device', 'MK7 Covert Ops Cloaking Device', 'MK9 Covert Ops Cloaking Device',
         "'Camouflage' Covert Ops Cloaking Device ", 'SOE Covert Ops Cloaking Device',
         "'Smoke' Covert Ops Cloaking Device ", 'MK1 Small Shield Extender', 'MK3 Small Shield Extender',
         'MK5 Small Shield Extender', 'MK7 Small Shield Extender', 'MK9 Small Shield Extender',
         "'Wolf' Small Shield Extenders", 'Caldari Navy Small Shield Extender',
         'Republic Fleet Small Shield Extender',
         "'Trapper' Small Shield Extender", 'MK5 Medium Shield Extender', 'MK7 Medium Shield Extender',
         'MK9 Medium Shield Extender', "'Canyon' Medium Shield Extender", 'Caldari Navy Medium Shield Extender',
         'Republic Fleet Medium Shield Extender', 'Dread Guristas Medium Shield Extender',
         'Patriot Medium Shield Extension Device', 'MK9 Large Shield Extender', "'Sheriff' Large Shield Extender",
         'Caldari Navy Large Shield Extender', 'Republic Fleet Large Shield Extender',
         "'Protector' Large Shield Extender ", 'Civilian Small Shield Booster', 'MK1 Small Shield Booster',
         'MK3 Small Shield Booster', 'MK5 Small Shield Booster', 'MK7 Small Shield Booster',
         'MK9 Small Shield Booster',
         "'Settler' Small Shield Booster", 'Caldari Navy Small Shield Booster',
         'Republic Fleet Small Shield Booster',
         'True Sansha Small Shield Booster', 'Dread Guristas Small Shield Booster',
         'Domination Small Shield Booster',
         'Veteran Small Shield Booster', 'Centii C-Type Small Shield Booster', 'Pithi C-Type Small Shield Booster',
         'Gistii C-Type Small Shield Booster', 'Civilian Medium Shield Booster', 'MK5 Medium Shield Booster',
         'MK7 Medium Shield Booster', 'MK9 Medium Shield Booster', "'Lone Ranger' Medium Shield Booster",
         'Caldari Navy Medium Shield Booster', 'Republic Fleet Medium Shield Booster',
         'True Sansha Medium Shield Booster', 'Dread Guristas Medium Shield Booster',
         'Domination Medium Shield Booster', "'Disaster' Medium Shield Booster",
         'Centum C-Type Medium Shield Booster',
         'Pithum C-Type Medium Shield Booster', 'Gistum C-Type Medium Shield Booster', 'MK9 Large Shield Booster',
         "'Outlaw' Large Shield Booster", 'Caldari Navy Large Shield Booster',
         'Republic Fleet Large Shield Booster',
         'True Sansha Large Shield Booster', 'Dread Guristas Large Shield Booster',
         'Domination Large Shield Booster',
         "'Seeker' Large Shield Booster ", 'Centus C-Type Large Shield Booster', 'Pith C-Type Large Shield Booster',
         'Gist C-Type Large Shield Booster', 'MK3 Small Microwarpdrive', 'MK5 Small Microwarpdrive',
         'MK7 Small Microwarpdrive', 'MK9 Small Microwarpdrive', "'Dealer' Small Microwarpdrive",
         'Federation Navy Small Microwarpdrive', 'Republic Fleet Small Microwarpdrive',
         'Shadow Serpentis Small Microwarpdrive', "'Scout' Small Microwarpdrive ",
         'Gistii C-Type Small Microwarpdrive',
         'MK5 Medium Microwarpdrive', 'MK7 Medium Microwarpdrive', 'MK9 Medium Microwarpdrive',
         "'Dealer' Medium Microwarpdrive", 'Federation Navy Medium Microwarpdrive',
         'Republic Fleet Medium Microwarpdrive', 'Shadow Serpentis Medium Microwarpdrive',
         "'Scout' Medium Microwarpdrive ", 'Gistum C-Type Medium Microwarpdrive', 'MK9 Large Microwarpdrive',
         "'Dealer' Large Microwarpdrive", 'Federation Navy Large Microwarpdrive',
         'Republic Fleet Large Microwarpdrive',
         "'Scout' Large Microwarpdrive ", 'Gist C-Type Large Microwarpdrive', 'Civilian Small Afterburner',
         'MK1 Small Afterburner', 'MK3 Small Afterburner', 'MK5 Small Afterburner', 'MK7 Small Afterburner',
         'MK9 Small Afterburner', 'Smuggler Small Afterburner', 'Federation Navy Small Afterburner',
         'Republic Fleet Small Afterburner', 'Shadow Serpentis Small Afterburner', "'Ranger' Small Afterburner ",
         'Centii C-Type Small Afterburner', 'Coreli C-Type Small Afterburner', 'Civilian Medium Afterburner',
         'MK5 Medium Afterburner', 'MK7 Medium Afterburner', 'MK9 Medium Afterburner',
         'Smuggler Medium Afterburner',
         'Federation Navy Medium Afterburner', 'Republic Fleet Medium Afterburner',
         'Shadow Serpentis Medium Afterburner', 'Domination Medium Afterburner', "'Ranger' Medium Afterburner ",
         'Centum C-Type Medium Afterburner', 'Corelum C-Type Medium Afterburner', 'MK9 Large Afterburner',
         'Smuggler Large Afterburner', 'Federation Navy Large Afterburner', 'Republic Fleet Large Afterburner',
         "'Ranger' Large Afterburner ", 'Centus C-Type Large Afterburner', 'Core C-Type Large Afterburner',
         'MK3 Warp Disruptor', 'MK5 Warp Disruptor', 'MK7 Warp Disruptor', 'MK9 Warp Disruptor',
         "'Interruptive' Warp Disruptor", 'Caldari Navy Warp Disruptor', 'Federation Navy Warp Disruptor',
         'Republic Fleet Warp Disruptor', 'True Sansha Warp Disruptor', 'Dark Blood Warp Disruptor',
         'Dread Guristas Warp Disruptor', 'Shadow Serpentis Warp Disruptor', "'Predator' Warp Disruptor ",
         'MK3 Small Capacitor Battery', 'MK5 Small Capacitor Battery', 'MK7 Small Capacitor Battery',
         'MK9 Small Capacitor Battery', "'Acolyth' Small Capacitor Battery ",
         'Republic Fleet Small Capacitor Battery',
         "'Demolish' Small Capacitor Battery ", 'Gistii C-Type Small Capacitor Batteries',
         'MK5 Medium Capacitor Battery', 'MK7 Medium Capacitor Battery', 'MK9 Medium Capacitor Battery',
         "'Acolyth' Medium Capacitor Battery ", 'Republic Fleet Medium Capacitor Battery',
         "'Demolish' Medium Capacitor Battery ", 'Gistum C-Type Medium Capacitor Battery',
         'MK9 Large Capacitor Battery', "'Acolyth' Large Capacitor Batteries",
         'Republic Fleet Large Capacitor Battery',
         'Domination Large Capacitor Battery', "'Demolish' Large Capacitor Battery ",
         'Gist C-Type Large Capacitor Battery', 'Civilian Stasis Webifier', 'MK3 Stasis Webifier',
         'MK5 Stasis Webifier', 'MK7 Stasis Webifier', 'MK9 Stasis Webifier', "'Interruptive' Stasis Webifier",
         'Caldari Navy Stasis Webifier', 'Federation Navy Stasis Webifier', 'Republic Fleet Stasis Webifier',
         'True Sansha Stasis Webifier', 'Dark Blood Stasis Webifier', 'Dread Guristas Stasis Webifier',
         'Shadow Serpentis Stasis Webifier', "'Predator' Stasis Webifier ", 'MK5 Adaptive Invulnerability Field',
         'MK7 Adaptive Invulnerability Field', 'MK9 Adaptive Invulnerability Field',
         'Posse Adaptive Invulnerability Field', 'Caldari Navy Adaptive Invulnerability Field',
         'Dread Guristas Adaptive Invulnerability Field', 'Domination Adaptive Invulnerability Field',
         "'Enterprise' Adaptive Invulnerability Field ", 'Pith C-Type Adaptive Invulnerability Field',
         'Gist C-Type Adaptive Invulnerability Field', 'MK5 Tracking Computer', 'MK7 Tracking Computer',
         'MK9 Tracking Computer', "'Marketeer' Tracking Computer", 'Federation Navy Tracking Computer',
         'Shadow Serpentis Tracking Computer', "'Eagle' Tracking Computer ", 'MK5 Drone Navigation Computer',
         'MK7 Drone Navigation Computer', 'MK9 Drone Navigation Computer', "'Decoder' Drone Navigation Computer ",
         'Federation Navy Drone Navigation Computer', "'Supervisor' Drone Navigation Computer ",
         'MK5 Omnidirectional Tracking Link', 'MK7 Omnidirectional Tracking Link',
         'MK9 Omnidirectional Tracking Link',
         "'Decoder' Omnidirectional Tracking Link ", 'Imperial Navy Omnidirectional Tracking Link',
         'Federation Navy Omnidirectional Tracking Link', "'Supervisor' Omnidirectional Tracking Link ",
         'MK5 Missile Guidance Computer', 'MK7 Missile Guidance Computer', 'MK9 Missile Guidance Computer',
         "'Elusive' Missile Guidance Computer ", 'Caldari Navy Missile Guidance Computer',
         "'Hook' Missile Guidance Computer ", 'MK1 Gyrostabilizer', 'MK3 Gyrostabilizer', 'MK5 Gyrostabilizer',
         'MK7 Gyrostabilizer', 'MK9 Gyrostabilizer', 'Basic Gyrostabilizer', 'Republic Fleet Gyrostabilizer',
         "'Rebirth' Gyrostabilizer", 'Gistum C-Type Gyrostabilizers', 'MK5 Damage Control', 'MK7 Damage Control',
         'MK9 Damage Control', 'Basic Damage Control', 'Imperial Navy Damage Control',
         'Federation Navy Damage Control',
         'Shadow Serpentis Damage Control', 'Sentient Damage Control', 'All-round Damage Control',
         'Civilian Small Armor Repairer', 'MK1 Small Armor Repairer', 'MK3 Small Armor Repairer',
         'MK5 Small Armor Repairer', 'MK7 Small Armor Repairer', 'MK9 Small Armor Repairer',
         'Gorget Small Armor Repairer', 'Imperial Navy Small Armor Repairer',
         'Federation Navy Small Armor Repairer',
         'Dark Blood Small Armor Repairer', 'Shadow Serpentis Small Armor Repairer',
         "'Knight' Small Armor Repairer ",
         'Corpii C-Type Small Armor Repairer', 'Coreli C-Type Small Armor Repairer',
         'Civilian Medium Armor Repairer',
         'MK5 Medium Armor Repairer', 'MK7 Medium Armor Repairer', 'MK9 Medium Armor Repairer',
         "'Gorget' Medium Armor Repairer ", 'Imperial Navy Medium Armor Repairer',
         'Federation Navy Medium Armor Repairer', 'Dark Blood Medium Armor Repairer',
         'Shadow Serpentis Medium Armor Repairer', "'Knight' Medium Armor Repairer ",
         'Corpum C-Type Medium Armor Repairer', 'Corelum C-Type Medium Armor Repairer', 'MK9 Large Armor Repairer',
         "'Gorget' Large Armor Repairer ", 'Imperial Navy Large Armor Repairer',
         'Federation Navy Large Armor Repairer',
         "'Chivalry' Large Armor Repairer", 'Corpus C-Type Large Armor Repairer',
         'Core C-Type Large Armor Repairer',
         'MK1 Heat Sink', 'MK3 Heat Sink', 'MK5 Heat Sink', 'MK7 Heat Sink', 'MK9 Heat Sink', 'Basic Heat Sink',
         'Imperial Navy Heat Sink', 'True Sansha Heat Sink', 'Dark Blood Heat Sink', "'Judgement' Heat Sink",
         'Centum C-Type Heat Sink', 'Corpum C-Type Heat Sink', 'MK1 Magnetic Field Stabilizer',
         'MK3 Magnetic Field Stabilizer', 'MK5 Magnetic Field Stabilizer', 'MK7 Magnetic Field Stabilizer',
         'MK9 Magnetic Field Stabilizer', 'Basic Magnetic Field Stabilizer',
         'Federation Navy Magnetic Field Stabilizer', 'Narcotics Magnetic Field Stabilizer',
         'Corelum C-Type Magnetic Field Stabilizer', 'MK1 Warp Core Stabilizer', 'MK3 Warp Core Stabilizer',
         'MK5 Warp Core Stabilizer', 'MK7 Warp Core Stabilizer', 'MK9 Warp Core Stabilizer',
         "'Aura' Warp Core Stabilizer", "'Natura' Warp Core Stabilizer", 'MK5 Adaptive Armor Hardener',
         'MK7 Adaptive Armor Hardener', 'MK9 Adaptive Armor Hardener', "'Pilfer' Adaptive Armor Hardener",
         'Imperial Navy Adaptive Armor Hardener', 'Federation Navy Adaptive Armor Hardener',
         'Dark Blood Adaptive Armor Hardener', 'Shadow Serpentis Adaptive Armor Hardener',
         "'Sparkly' Adaptive Armor Hardener ", 'Corpus C-Type Adaptive Armor Hardener',
         'Core C-Type Adaptive Armor Hardener', 'MK1 100mm Reinforced Steel Plate',
         'MK3 100mm Reinforced Steel Plate',
         'MK5 100mm Reinforced Steel Plate', 'MK7 100mm Reinforced Steel Plate', 'MK9 100mm Reinforced Steel Plate',
         "'Abatis' 100mm Reinforced Steel Plate", 'Imperial Navy 100mm Reinforced Steel Plate',
         'Federation Navy 100mm Reinforced Steel Plate', "'Fort' 100mm Reinforced Steel Plate",
         'MK3 200mm Reinforced Steel Plate', 'MK5 200mm Reinforced Steel Plate', 'MK7 200mm Reinforced Steel Plate',
         'MK9 200mm Reinforced Steel Plate', "'Abatis' 200mm Reinforced Steel Plate ",
         'Imperial Navy 200mm Reinforced Steel Plate', 'Federation Navy 200mm Reinforced Steel Plate',
         "'Citadella' 200mm Reinforced Steel Plate ", 'MK5 400mm Reinforced Steel Plate',
         'MK7 400mm Reinforced Steel Plate', 'MK9 400mm Reinforced Steel Plate',
         "'Bastion' 400mm Reinforced Steel Plate", 'Imperial Navy 400mm Reinforced Steel Plate',
         'Federation Navy 400mm Reinforced Steel Plate', 'Hansen 400mm Reinforced Steel Plate',
         'MK5 800mm Reinforced Steel Plate', 'MK7 800mm Reinforced Steel Plate', 'MK9 800mm Reinforced Steel Plate',
         "'Bastion' 800mm Reinforced Steel Plate ", 'Imperial Navy 800mm Reinforced Steel Plate',
         'Federation Navy 800mm Reinforced Steel Plate', 'Dark Blood 800mm Reinforced Steel Plate',
         "'Hansen' 800mm Reinforced Steel Plate ", 'MK9 1600mm Reinforced Steel Plate',
         "'Bailey' 1600mm Reinforced Steel Plate", 'Imperial Navy 1600mm Reinforced Steel Plate',
         'Federation Navy 1600mm Reinforced Steel Plate', 'Dark Blood 1600mm Reinforced Steel Plate',
         "'Core' 1600mm Reinforced Steel Plate ", 'MK1 Ballistic Control System', 'MK3 Ballistic Control System',
         'MK5 Ballistic Control System', 'MK7 Ballistic Control System', 'MK9 Ballistic Control System',
         'Full Duplex Ballistic Control System', 'Caldari Navy Ballistic Control System',
         'Republic Fleet Ballistic Control System', 'Dread Guristas Ballistic Control System',
         'Domination Ballistic Control System', "'Ironblood' Damage Control System",
         'Pithum C-Type Ballistic Control System', 'MK3 Drone Damage Amplifier', 'MK5 Drone Damage Amplifier',
         'MK7 Drone Damage Amplifier', 'MK9 Drone Damage Amplifier', 'Bat Drone Damage Amplifier',
         'Imperial Navy Drone Damage Amplifier', 'Federation Navy Drone Damage Amplifier',
         'Dread Guristas Drone Damage Amplifier', 'Sentient Drone Damage Amplifier',
         "'Nestworm' Drone Damage Amplifier ", 'MK3 Inertial Stabilizer', 'MK5 Inertial Stabilizer',
         'MK7 Inertial Stabilizer', 'MK9 Inertial Stabilizer', 'Basic Inertial Stabilizer',
         'Federation Navy Inertial Stabilizer', 'Republic Fleet Inertial Stabilizer',
         'Synthetic Hull Inertial Stabilizer', 'MK1 Reactive Armor Hardener', 'MK3 Reactive Armor Hardener',
         'MK5 Reactive Armor Hardener', 'MK7 Reactive Armor Hardener', 'MK9 Reactive Armor Hardener',
         "'Moat' Reactive Armor Hardener", 'Imperial Navy Reactive Armor Hardener',
         'Federation Navy Reactive Armor Hardener', 'Dark Blood Reactive Armor Hardener',
         'Shadow Serpentis Reactive Armor Hardener', "'Sparkly' Reactive Armor Hardener ",
         'Corpum C-Type Reactive Armor Hardener', 'Corelum C-Type Reactive Armor Hardener',
         'MK1 Reactive Shield Hardener', 'MK3 Reactive Shield Hardener', 'MK5 Reactive Shield Hardener',
         'MK7 Reactive Shield Hardener', 'MK9 Reactive Shield Hardener', 'Challenger Reactive Shield Hardener',
         'Caldari Navy Reactive Shield Hardener', 'Republic Fleet Reactive Shield Hardener',
         'True Sansha Reactive Shield Hardener', 'Dread Guristas Reactive Shield Hardener',
         'Domination Reactive Shield Hardener', "'Enterprise' Reactive Shield Hardener ",
         'Pithum C-Type Reactive Shield Hardener', 'Gistum C-Type Reactive Shield Hardener',
         'MK5 Small Shield Field Module', 'MK7 Small Shield Field Module', 'MK9 Small Shield Field Module',
         "'Crucible' Small Shield Field Module", 'Caldari Navy Small Shield Field Module',
         'Republic Fleet Small Shield Field Module', "'Mirror' Small Shield Field Module ",
         'Pithi C-Type Small Shield Field Module', 'Gistii C-Type Small Shield Field Module',
         'MK5 Medium Shield Field Module', 'MK7 Medium Shield Field Module', 'MK9 Medium Shield Field Module',
         "'Crucible' Medium Shield Field Module", "'Mirror' Medium Shield Field Module ",
         'Pithum C-Type Medium Shield Field Module', 'Gistum C-Type Medium Shield Field Module',
         'MK7 Large Shield Field Module', 'MK9 Large Shield Field Module', "'Crucible' Large Shield Field Module",
         "'Mirror' Large Shield Field Module ", 'Pith C-Type Large Shield Field Module',
         'Gist C-Type Large Shield Field Module', 'MK5 Small Armor Link Module', 'MK7 Small Armor Link Module',
         'MK9 Small Armor Link Module', "'Hustler' Small Armor Link Module",
         'Imperial Navy Small Armor Link Module',
         "'Bloodline' Small Armor Link Module ", 'MK5 Medium Armor Link Module', 'MK7 Medium Armor Link Module',
         'MK9 Medium Armor Link Module', "'Hustler' Medium Armor Link Module",
         "'Bloodline' Medium Armor Link Module ",
         'Corpum C-Type Medium Armor Link Module', 'Corelum C-Type Medium Armor Link Module',
         'MK7 Large Armor Link Module', 'MK9 Large Armor Link Module', "'Hustler' Large Armor Link Module",
         "'Bloodline' Large Armor Link Module ", 'Corpus C-Type Large Armor Link Module',
         'Core C-Type Large Armor Link Module', 'MK5 Small Group Shield Booster', 'MK7 Small Group Shield Booster',
         'MK9 Small Group Shield Booster', "'Settler' Small Group Shield Booster",
         "'Bannerman' Small Group Shield Booster ", 'MK5 Medium Group Shield Booster',
         'MK7 Medium Group Shield Booster', "'Settler' Medium Group Shield Booster",
         'Republic Fleet Medium Group Shield Booster', "'Bannerman' Medium Group Shield Booster ",
         'MK7 Large Group Shield Booster ', 'MK9 Large Group Shield Booster ',
         "'Settler' Large Group Shield Booster ",
         'Caldari Navy Large Group Shield Booster ', 'Republic Fleet Large Group Shield Booster',
         'True Sansha Large Group Shield Booster ', 'Dread Guristas Large Group Shield Booster ',
         "'Bannerman' Large Group Shield Booster ", 'MK5 Small Group Armor Repairer',
         'MK7 Small Group Armor Repairer',
         "'Repairman' Small Group Armor Repairer ", 'Imperial Navy Small Group Armor Repairer',
         "'Engineer' Small Group Armor Repairer ", 'MK5 Medium Group Armor Repairer',
         'MK7 Medium Group Armor Repairer',
         "'Repairman' Medium Group Armor Repairer ", 'Imperial Navy Medium Group Armor Repairer',
         'Federation Navy Medium Group Armor Repairer', "'Engineer' Medium Group Armor Repairer ",
         'MK7 Large Group Armor Repairer ', 'MK9 Large Group Armor Repairer ',
         "'Repairman' Large Group Armor Repairer ", "'Engineer' Large Group Armor Repairer ",
         'MK5 Small Group Capacitor Transmitter', 'MK7 Small Group Capacitor Transmitter',
         "'Ghost' Small Group Capacitor Transmitter ", 'Centii C-Type Small Group Capacitor Transmitter',
         'MK5 Medium Group Capacitor Transmitter', 'MK7 Medium Group Capacitor Transmitter',
         "'Ghost' Medium Group Capacitor Transmitter ", 'Centum C-Type Medium Group Capacitor Transmitter',
         'MK7 Large Group Capacitor Transmitter ', 'MK9 Large Group Capacitor Transmitter ',
         "'Ghost' Large Group Capacitor Transmitter ", "'Prayer' Large Group Capacitor Transmitter ",
         'Centum C-Type Large Group Capacitor Transmitter ', "'The Returned' Macro Particle Stabilizer",
         'Yan-Jung Macro Particle Stabilizer', "'Wei' C Macro Particle Stabilizer",
         'Railgun Collision Accelerator I',
         'Railgun Collision Accelerator II', 'Railgun Ambit Extension I', 'Railgun Ambit Extension II',
         'Railgun Discharge Elutriation I', 'Railgun Discharge Elutriation II', 'Railgun Burst Aerator I',
         'Railgun Burst Aerator II', 'Railgun Burst Aerator III', 'Algid Railgun Administrations Unit I',
         'Algid Railgun Administrations Unit II', 'Laser Collision Accelerator I', 'Laser Collision Accelerator II',
         'Laser Ambit Extension I', 'Laser Ambit Extension II', 'Laser Discharge Elutriation I',
         'Laser Discharge Elutriation II', 'Laser Burst Aerator I', 'Laser Burst Aerator II',
         'Algid Energy Administrations Unit I', 'Algid Energy Administrations Unit II',
         'Algid Energy Administrations Unit IV', 'Cannon Collision Accelerator I',
         'Cannon Collision Accelerator II',
         'Cannon Collision Accelerator III', 'Cannon Ambit Extension I', 'Cannon Ambit Extension II',
         'Cannon Ambit Extension III', 'Cannon Burst Aerator I', 'Cannon Burst Aerator II',
         'Cannon Burst Aerator III',
         'Cannon Metastasis Adjuster I', 'Cannon Metastasis Adjuster II', 'Decomposer Collision Accelerator I',
         'Decomposer Collision Accelerator II', 'Decomposer Collision Accelerator III',
         'Decomposer Collision Accelerator IV', 'Decomposer Ambit Extension I', 'Decomposer Ambit Extension II',
         'Decomposer Ambit Extension III', 'Decomposer Discharge Elutriation I',
         'Decomposer Discharge Elutriation II',
         'Decomposer Burst Aerator I', 'Decomposer Burst Aerator II', 'Decomposer Burst Aerator III',
         'Decomposer Algid Hybrid Administrations Unit I', 'Decomposer Algid Hybrid Administrations Unit II',
         'Warhead Flare Catalyst I', 'Warhead Flare Catalyst II', 'Warhead Calefaction Catalyst I',
         'Warhead Calefaction Catalyst II', 'Warhead Calefaction Catalyst III', 'Warhead Calefaction Catalyst IV',
         'Warhead Rigor Catalyst I', 'Warhead Rigor Catalyst II', 'Rocket Fuel Cache Partition I',
         'Rocket Fuel Cache Partition II', 'Rocket Fuel Cache Partition III', 'Hydraulic Bay Thrusters I',
         'Hydraulic Bay Thrusters II', 'Bay Loading Accelerator I', 'Bay Loading Accelerator II',
         'Bay Loading Accelerator III', 'Bay Loading Accelerator IV', 'Core Defense Operational Solidifier I',
         'Core Defense Operational Solidifier II', 'Core Defense Operational Solidifier III',
         'Core Defense Charge Economizer I', 'Core Defense Charge Economizer II',
         'Core Defense Capacitor Safeguard I',
         'Core Defense Capacitor Safeguard II', 'Core Defense Capacitor Safeguard III',
         'Core Defense Capacitor Safeguard IV', 'Core Defense Field Extender I', 'Core Defense Field Extender II',
         'Core Defense Field Extender III', 'Anti-Explosive Screen Reinforcer I',
         'Anti-Explosive Screen Reinforcer II',
         'Anti-EM Screen Reinforcer I', 'Anti-EM Screen Reinforcer II', 'Anti-EM Screen Reinforcer III',
         'Anti-EM Screen Reinforcer IV', 'Anti-Kinetic Screen Reinforcer I', 'Anti-Kinetic Screen Reinforcer II',
         'Anti-Thermal Screen Reinforcer I', 'Anti-Thermal Screen Reinforcer II', 'Nanobot Accelerator I',
         'Nanobot Accelerator II', 'Auxiliary Nano Pump I', 'Auxiliary Nano Pump II', 'Repair Augmentor I',
         'Repair Augmentor II', 'Trimark Armor Pump I', 'Trimark Armor Pump II', 'Anti-Explosive Pump I',
         'Anti-Explosive Pump II', 'Anti-EM Pump I', 'Anti-EM Pump II', 'Anti-Kinetic Pump I',
         'Anti-Kinetic Pump II',
         'Anti-Thermal Pump I', 'Anti-Thermal Pump II', 'Dynamic Fuel Valve I', 'Dynamic Fuel Valve II',
         'Dynamic Fuel Valve III', 'Auxiliary Thrusters I', 'Auxiliary Thrusters II', 'Auxiliary Thrusters III',
         'Auxiliary Thrusters IV', 'Polycarbon Engine Housing I', 'Polycarbon Engine Housing II',
         'Polycarbon Engine Housing III', 'Cargohold Optimization I', 'Cargohold Optimization II',
         'Cargohold Optimization III', 'Cargohold Optimization IV', 'Higgs Anchor I', 'Higgs Anchor II',
         'Warp Core Optimizer I', 'Warp Core Optimizer II', 'Warp Core Optimizer III', 'Warp Core Optimizer IV',
         'Hyperspatial Velocity Optimizer I', 'Hyperspatial Velocity Optimizer II',
         'Hyperspatial Velocity Optimizer III', 'Hyperspatial Velocity Optimizer IV', 'Semiconductor Memory Cell I',
         'Semiconductor Memory Cell II', 'Semiconductor Memory Cell III', 'Semiconductor Memory Cell IV',
         'Capacitor Control Circuit I', 'Capacitor Control Circuit II', 'Capacitor Control Circuit III',
         'Capacitor Control Circuit IV', 'Ancillary Powergrid Router I', 'Ancillary Powergrid Router II',
         'Ancillary Powergrid Router III', 'Targeting System Subcontroller I', 'Targeting System Subcontroller II',
         'Targeting System Subcontroller III', 'Gravity Capacitor Upgrade I', 'Gravity Capacitor Upgrade II',
         'Gravity Capacitor Upgrade III', 'Emission Scope Sharpener I', 'Emission Scope Sharpener II',
         'Emission Scope Sharpener III', 'Miner Efficiency Upgrade I', 'Miner Efficiency Upgrade II',
         'Miner Efficiency Upgrade III', 'Miner Efficiency Upgrade IV', 'Miner Circulation Accelerator I',
         'Miner Circulation Accelerator II', 'Miner Circulation Accelerator III',
         'Miner Circulation Accelerator IV',
         'Miner Range Controller I', 'Miner Range Controller II', 'Miner Algid Optimizer I',
         'Miner Algid Optimizer II',
         'Transverse Bulkhead I', 'Transverse Bulkhead II', 'Transverse Bulkhead III',
         'Anti-Explosive Transverse Bulkhead I', 'Anti-Explosive Transverse Bulkhead II',
         'Anti-EM Transverse Bulkhead I', 'Anti-EM Transverse Bulkhead II', 'Anti-Kinetic Transverse Bulkhead I',
         'Anti-Kinetic Transverse Bulkhead II', 'Anti-Thermal Transverse Bulkhead I',
         'Anti-Thermal Transverse Bulkhead II', 'Sentry Damage Augmentor I', 'Sentry Damage Augmentor II',
         'Sentry Damage Augmentor III', 'Sentry Damage Augmentor IV', 'Drone Scope Chip I', 'Drone Scope Chip II',
         'Drone Scope Chip III', 'Drone Speed Augmentor I', 'Drone Speed Augmentor II', 'Drone Speed Augmentor III',
         'Drone Control Range Augmentor I', 'Drone Control Range Augmentor II', 'Drone Control Range Augmentor III',
         'Drone Control Range Augmentor IV', 'Civilian Acolyte', 'MK3 Acolyte', 'MK5 Acolyte', 'MK7 Acolyte',
         'MK9 Acolyte', 'Imperial Navy Acolyte', 'Civilian Hornet', 'MK3 Hornet', 'MK5 Hornet', 'MK7 Hornet',
         'Caldari Navy Hornet', 'Civilian Hobgoblin', 'MK3 Hobgoblin', 'MK5 Hobgoblin', 'MK7 Hobgoblin',
         'Federation Navy Hobgoblin', 'Civilian Warrior', 'MK3 Warrior', 'MK5 Warrior', 'MK7 Warrior',
         'Republic Fleet Warrior', 'MK5 Infiltrator', 'MK7 Infiltrator', 'MK9 Infiltrator',
         'Imperial Navy Infiltrator',
         'MK5 Vespa', 'MK7 Vespa', 'Caldari Navy Vespa', 'MK5 Hammerhead', 'MK7 Hammerhead', 'MK9 Hammerhead',
         'Federation Navy Hammerhead', 'MK5 Valkyrie', 'MK7 Valkyrie', 'MK9 Valkyrie', 'Republic Fleet Valkyrie',
         'MK7 Praetor', 'MK9 Praetor', 'Imperial Navy Praetor', 'MK7 Wasp', 'MK9 Wasp', 'MK7 Ogre', 'MK9 Ogre',
         'MK7 Berserker', 'MK9 Berserker', 'MK7 Curator', 'MK7 Warden', 'MK9 Warden', 'MK7 Guard',
         'Federation Navy Guard', 'MK7 Bouncer', 'MK9 Bouncer', 'Republic Fleet Bouncer', 'Capsuleer Outpost',
         'Standard Standup Small Missile Launcher', 'Standard Standup Medium Missile Launcher',
         'Standard Standup Large Missile Launcher', 'Standard Standup Stasis Webifier',
         'Standard Standup Warp Disruptor', 'Standard Standup Energy Neutralizer', 'Production Service Center',
         'Structure Construction Parts', 'Structure Hangar Array', 'Structure Storage Bay', 'Structure Laboratory',
         'Structure Factory', 'Structure Repair Facility', 'Structure Reprocessing Plant', 'Structure Docking Bay',
         'Structure Market Network', 'Structure Medical Center', 'Structure Office Center',
         'Structure Mission Network',
         'Structure Electromagnetic Sensor', 'Structure Acceleration Coils', 'Structure Advertisement Nexus',
         'Datacore - Amarrian Starship Engineering', 'Datacore - Electromagnetic Physics',
         'Datacore - Gallentean Starship Engineering', 'Datacore - High Energy Physics',
         'Datacore - Rocket Science',
         'Datacore - Mechanical Engineering', 'Datacore - Laser Physics', 'Datacore - Caldari Starship Engineering',
         'Datacore - Minmatar Starship Engineering', 'Metal Scraps', 'Reinforced Metal Scraps', 'Ancient Remains',
         'PLEX', 'Divine Redemption', 'True Divine Trial', 'Spark of Rebellion', 'For Freedom', 'Matar Reborn',
         'Angel or Devil', 'Disaster Relief', "A Soldier's Way", 'Bad Hare Day', 'Mega Corporation',
         'For Patriotism',
         'Modern World', 'Business Magnate', 'Super Soft Drink', "'Conqueror' Supply Chest",
         "'Devout' Supply Chest",
         "'Martyr' Supply Chest", "'Patriot' Supply Chest", "'Soldier' Supply Chest", "'Hunter' Supply Chest",
         "'Quafe Exclusive' Supply Chest", "'Investor' Supply Chest", "'Detective' Supply Chest",
         "'Revolt' Supply Chest", "'Survivor' Supply Chest", "'Guardian' Supply Chest",
         'Chip: Cognitive Neuroscience Lv. 5', 'Chip: Advanced Cognitive Neuroscience Lv. 5',
         'Chip: Expert Cognitive Neuroscience Lv. 5', 'Tritanium', 'Pyerite', 'Mexallon', 'Isogen', 'Nocxium',
         'Zydrine', 'Megacyte', 'Morphite', 'Charred Micro Circuit', 'Fried Interface Circuit',
         'Tripped Power Circuit',
         'Smashed Trigger Unit', 'Damaged Close-in Weapon System', 'Scorched Telemetry Processor',
         'Contaminated Lorentz Fluid', 'Conductive Polymer', 'Contaminated Nanite Polymer',
         'Defective Current Pump',
         'Lustering Alloy', 'Sheen Compound', 'Gleaming Alloy', 'Condensed Alloy', 'Precious Alloy',
         'Motley Compound',
         'Fiber Composite', 'Lucent Compound', 'Opulent Compound', 'Glossy Compound', 'Crystal Compound',
         'Dark Compound', 'Reactive Gas', 'Noble Gas', 'Base Metals', 'Heavy Metals', 'Noble Metals',
         'Reactive Metals',
         'Toxic Metals', 'Industrial Fibers', 'Supertensile Plastics', 'Polyaramids', 'Coolant', 'Condensates',
         'Construction Blocks', 'Nanites', 'Silicate Glass', 'Smartfab Units', 'Heavy Water', 'Suspended Plasma',
         'Liquid Ozone', 'Ionic Solutions', 'Oxygen Isotopes', 'Plasmoids', 'Lv.4 Amarr Ship Debris',
         'Lv.5 Amarr Ship Debris', 'Lv.6 Amarr Ship Debris', 'Lv.7 Amarr Ship Debris', 'Lv.8 Amarr Ship Debris',
         'Lv.9 Amarr Ship Debris', 'Lv.10 Amarr Ship Debris', 'Lv.4 Caldari Ship Debris',
         'Lv.5 Caldari Ship Debris',
         'Lv.6 Caldari Ship Debris', 'Lv.7 Caldari Ship Debris', 'Lv.8 Caldari Ship Debris',
         'Lv.9 Caldari Ship Debris',
         'Lv.10 Caldari Ship Debris', 'Lv.4 Gallente Ship Debris', 'Lv.5 Gallente Ship Debris',
         'Lv.6 Gallente Ship Debris', 'Lv.7 Gallente Ship Debris', 'Lv.8 Gallente Ship Debris',
         'Lv.9 Gallente Ship Debris', 'Lv.10 Gallente Ship Debris', 'Lv.4 Minmatar Ship Debris',
         'Lv.5 Minmatar Ship Debris', 'Lv.6 Minmatar Ship Debris', 'Lv.7 Minmatar Ship Debris',
         'Lv.8 Minmatar Ship Debris', 'Lv.9 Minmatar Ship Debris', 'Lv.10 Minmatar Ship Debris',
         'Small Damaged ORE Hull', 'Medium Damaged ORE Hull', 'Large Damaged ORE Hull', 'Guristas Ship Debris',
         'Sansha Ship Debris', 'Angel Ship Debris', 'Serpentis Ship Debris', 'SOE Ship Debris',
         "Mordu's Legion Ship Debris", 'Small Damaged InterBus Hull', 'Medium Damaged InterBus Hull',
         'Large Damaged InterBus Hull', 'Veldspar', 'Compressed Veldspar', 'Scordite', 'Compressed Scordite',
         'Pyroxeres', 'Compressed Pyroxeres', 'Plagioclase', 'Compressed Plagioclase', 'Omber', 'Compressed Omber',
         'Kernite', 'Compressed Kernite', 'Jaspet', 'Compressed Jaspet', 'Hemorphite', 'Compressed Hemorphite',
         'Hedbergite', 'Compressed Hedbergite', 'Spodumain', 'Compressed Spodumain', 'Dark Ochre',
         'Compressed Dark Ochre', 'Gneiss', 'Compressed Gneiss', 'Crokite', 'Compressed Crokite', 'Bistot',
         'Compressed Bistot', 'Arkonor', 'Compressed Arkonor', 'Mercoxit', 'Compressed Mercoxit',
         'Griffin Blueprint',
         'Bantam Blueprint', 'Bantam II Blueprint', 'Condor II Blueprint', 'Condor Interceptor Blueprint',
         'Condor II Interceptor Blueprint', 'Merlin Assault Blueprint', 'Manticore Blueprint',
         'Manticore II Blueprint',
         'Heron Covert Ops Blueprint', 'Vigil Blueprint', 'Burst Blueprint', 'Burst II Blueprint',
         'Slasher II Blueprint', 'Slasher Interceptor Blueprint', 'Slasher II Interceptor Blueprint',
         'Breacher Assault Blueprint', 'Hound Blueprint', 'Hound II Blueprint', 'Probe Covert Ops Blueprint',
         'Crucifier Blueprint', 'Inquisitor Blueprint', 'Inquisitor II Blueprint', 'Executioner II Blueprint',
         'Executioner Interceptor Blueprint', 'Executioner II Interceptor Blueprint', 'Punisher Assault Blueprint',
         'Purifier Blueprint', 'Purifier II Blueprint', 'Magnate Covert Ops Blueprint', 'Maulus Blueprint',
         'Navitas Blueprint', 'Navitas II Blueprint', 'Atron II Blueprint', 'Atron Interceptor Blueprint',
         'Atron II Interceptor Blueprint', 'Incursus Assault Blueprint', 'Nemesis Blueprint',
         'Nemesis II Blueprint',
         'Imicus Covert Ops Blueprint', 'Worm Blueprint', 'Dramiel Blueprint', 'Cruor Blueprint',
         'Astero Blueprint',
         'Garmur Blueprint', 'Succubus Blueprint', 'Daredevil Blueprint', 'Cormorant Guardian Blueprint',
         'Corax Blueprint', 'Cormorant II Blueprint', 'Cormorant Navy Issue Blueprint', 'Corax Assault Blueprint',
         'Corax Sniper Blueprint', 'Cormorant Covert Ops Blueprint', 'Thrasher Guardian Blueprint',
         'Talwar Blueprint',
         'Thrasher II Blueprint', 'Thrasher Fleet Issue Blueprint', 'Talwar Assault Blueprint',
         'Talwar Sniper Blueprint', 'Thrasher Covert Ops Blueprint', 'Coercer Guardian Blueprint',
         'Dragoon Blueprint',
         'Coercer II Blueprint', 'Coercer Navy Issue Blueprint', 'Dragoon Assault Blueprint',
         'Coercer Covert Ops Blueprint', 'Catalyst Guardian Blueprint', 'Algos Blueprint', 'Catalyst II Blueprint',
         'Catalyst Navy Issue Blueprint', 'Algos Assault Blueprint', 'Algos Sniper Blueprint',
         'Catalyst Covert Ops Blueprint', 'Moa Guardian Blueprint', 'Moa II Guardian Blueprint',
         'Blackbird Blueprint',
         'Osprey Blueprint', 'Caracal Blueprint', 'Moa Blueprint', 'Caracal Navy Issue Blueprint',
         'Caracal Sniper Blueprint', 'Blackbird Covert Ops Blueprint', 'Blackbird II Covert Ops Blueprint',
         'Rupture Guardian Blueprint', 'Rupture II Guardian Blueprint', 'Bellicose Blueprint', 'Scythe Blueprint',
         'Stabber Blueprint', 'Stabber Fleet Issue Blueprint', 'Rupture Blueprint', 'Stabber Sniper Blueprint',
         'Bellicose Covert Ops Blueprint', 'Maller Guardian Blueprint', 'Maller II Guardian Blueprint',
         'Arbitrator Blueprint', 'Augoror Blueprint', 'Omen Blueprint', 'Maller Blueprint',
         'Omen Navy Issue Blueprint',
         'Omen Sniper Blueprint', 'Arbitrator Covert Ops Blueprint', 'Arbitrator II Covert Ops Blueprint',
         'Thorax Guardian Blueprint', 'Thorax II Guardian Blueprint', 'Celestis Blueprint', 'Exequror Blueprint',
         'Vexor Blueprint', 'Vexor Navy Issue Blueprint', 'Thorax Blueprint', 'Vexor Sniper Blueprint',
         'Celestis Covert Ops Blueprint', 'Thorax Prototype Blueprint', 'Gila Blueprint', 'Cynabal Blueprint',
         'Ashimmu Blueprint', 'Stratios Blueprint', 'Orthrus Blueprint', 'Phantasm Blueprint', 'Vigilant Blueprint',
         'Ferox Guardian Blueprint', 'Ferox II Guardian Blueprint', 'Naga Blueprint', 'Drake Logistics Blueprint',
         'Ferox Blueprint', 'Drake Blueprint', 'Cyclone Guardian Blueprint', 'Cyclone II Guardian Blueprint',
         'Tornado Blueprint', 'Tornado II Blueprint', 'Hurricane Logistics Blueprint', 'Cyclone Blueprint',
         'Hurricane Blueprint', 'Hurricane Prototype Blueprint', 'Prophecy Guardian Blueprint',
         'Prophecy II Guardian Blueprint', 'Oracle Blueprint', 'Oracle II Blueprint',
         'Harbinger Logistics Blueprint',
         'Prophecy Blueprint', 'Harbinger Blueprint', 'Harbinger Prototype Blueprint',
         'Myrmidon Guardian Blueprint',
         'Myrmidon II Guardian Blueprint', 'Talos Blueprint', 'Talos II Blueprint', 'Brutix Logistics Blueprint',
         'Myrmidon Blueprint', 'Brutix Blueprint', 'Scorpion Blueprint', 'Raven Striker Blueprint',
         'Rokh Blueprint',
         'Raven Blueprint', 'Typhoon Blueprint', 'Tempest Blueprint', 'Armageddon Blueprint',
         'Apocalypse Striker Blueprint', 'Abaddon Blueprint', 'Megathron Striker Blueprint', 'Dominix Blueprint',
         'Megathron Blueprint', 'Hyperion Blueprint', 'Rattlesnake Blueprint', 'Machariel Blueprint',
         'Bhaalgorn Blueprint', 'Nestor Blueprint', 'Barghest Blueprint', 'Vindicator Blueprint', 'Tayra Blueprint',
         'Badger Blueprint', 'Badger II Blueprint', 'Mammoth Blueprint', 'Wreathe II Blueprint',
         'Bestower Blueprint',
         'Sigil Blueprint', 'Kryos Blueprint', 'Nereus Blueprint', 'Nereus High Mobility Blueprint',
         'Nereus Combat Blueprint', 'Nereus Hauling Blueprint', 'Imicus High Mobility Blueprint',
         'Humpback High Mobility Blueprint', 'Humpback Hauling Blueprint', 'Humpback Combat Blueprint',
         'Retriever Blueprint', 'Procurer Blueprint', 'Covetor Blueprint', 'Venture Blueprint',
         'Venture II Blueprint',
         'Venture III Blueprint', 'MK5 Cloaking Device Blueprint', 'MK7 Cloaking Device Blueprint',
         'MK9 Cloaking Device Blueprint', 'MK5 Covert Ops Cloaking Device Blueprint',
         'MK7 Covert Ops Cloaking Device Blueprint', 'MK9 Covert Ops Cloaking Device Blueprint',
         'MK5 Small Shield Field Module Blueprint', 'MK7 Small Shield Field Module Blueprint',
         'MK9 Small Shield Field Module Blueprint', 'MK5 Medium Shield Field Module Blueprint',
         'MK7 Medium Shield Field Module Blueprint', 'MK9 Medium Shield Field Module Blueprint',
         'MK7 Large Shield Field Module Blueprint', 'MK5 Small Armor Link Module Blueprint',
         'MK7 Small Armor Link Module Blueprint', 'MK5 Medium Armor Link Module Blueprint',
         'MK7 Medium Armor Link Module Blueprint', 'MK9 Medium Armor Link Module Blueprint',
         'MK7 Large Armor Link Module Blueprint', 'MK5 Small Group Shield Booster Blueprint',
         'MK7 Small Group Shield Booster Blueprint', 'MK5 Medium Group Shield Booster Blueprint',
         'MK7 Medium Group Shield Booster Blueprint', 'MK9 Medium Group Shield Booster Blueprint',
         'MK7 Large Group Shield Booster  Blueprint', 'MK9 Large Group Shield Booster  Blueprint',
         'MK5 Small Group Armor Repairer Blueprint', 'MK7 Small Group Armor Repairer Blueprint',
         'MK5 Medium Group Armor Repairer Blueprint', 'MK7 Medium Group Armor Repairer Blueprint',
         'MK9 Medium Group Armor Repairer Blueprint', 'MK7 Large Group Armor Repairer  Blueprint',
         'MK9 Large Group Armor Repairer  Blueprint', 'MK5 Small Group Capacitor Transmitter Blueprint',
         'MK7 Small Group Capacitor Transmitter Blueprint', 'MK9 Small Group Capacitor Transmitter Blueprint',
         'MK5 Medium Group Capacitor Transmitter Blueprint', 'MK7 Medium Group Capacitor Transmitter Blueprint',
         'MK9 Medium Group Capacitor Transmitter Blueprint', 'MK7 Large Group Capacitor Transmitter  Blueprint',
         'Railgun Collision Accelerator I Blueprint', 'Railgun Collision Accelerator II Blueprint',
         'Railgun Collision Accelerator III Blueprint', 'Railgun Ambit Extension I Blueprint',
         'Railgun Ambit Extension II Blueprint', 'Railgun Ambit Extension III Blueprint',
         'Railgun Discharge Elutriation I Blueprint', 'Railgun Discharge Elutriation II Blueprint',
         'Railgun Discharge Elutriation III Blueprint', 'Railgun Burst Aerator I Blueprint',
         'Railgun Burst Aerator II Blueprint', 'Railgun Burst Aerator III Blueprint',
         'Algid Railgun Administrations Unit I Blueprint', 'Algid Railgun Administrations Unit II Blueprint',
         'Algid Railgun Administrations Unit III Blueprint', 'Laser Collision Accelerator I Blueprint',
         'Laser Collision Accelerator II Blueprint', 'Laser Collision Accelerator III Blueprint',
         'Laser Ambit Extension I Blueprint', 'Laser Ambit Extension II Blueprint',
         'Laser Ambit Extension III Blueprint', 'Laser Discharge Elutriation I Blueprint',
         'Laser Discharge Elutriation II Blueprint', 'Laser Discharge Elutriation III Blueprint',
         'Laser Burst Aerator I Blueprint', 'Laser Burst Aerator II Blueprint', 'Laser Burst Aerator III Blueprint',
         'Algid Energy Administrations Unit I Blueprint', 'Algid Energy Administrations Unit II Blueprint',
         'Algid Energy Administrations Unit III Blueprint', 'Cannon Collision Accelerator I Blueprint',
         'Cannon Collision Accelerator II Blueprint', 'Cannon Collision Accelerator III Blueprint',
         'Cannon Ambit Extension I Blueprint', 'Cannon Ambit Extension II Blueprint',
         'Cannon Ambit Extension III Blueprint', 'Cannon Burst Aerator I Blueprint',
         'Cannon Burst Aerator II Blueprint', 'Cannon Burst Aerator III Blueprint',
         'Cannon Metastasis Adjuster I Blueprint', 'Cannon Metastasis Adjuster II Blueprint',
         'Cannon Metastasis Adjuster III Blueprint', 'Decomposer Collision Accelerator I Blueprint',
         'Decomposer Collision Accelerator II Blueprint', 'Decomposer Collision Accelerator III Blueprint',
         'Decomposer Ambit Extension I Blueprint', 'Decomposer Ambit Extension II Blueprint',
         'Decomposer Ambit Extension III Blueprint', 'Decomposer Discharge Elutriation I Blueprint',
         'Decomposer Discharge Elutriation II Blueprint', 'Decomposer Discharge Elutriation III Blueprint',
         'Decomposer Burst Aerator I Blueprint', 'Decomposer Burst Aerator II Blueprint',
         'Decomposer Burst Aerator III Blueprint', 'Decomposer Algid Hybrid Administrations Unit I Blueprint',
         'Decomposer Algid Hybrid Administrations Unit II Blueprint',
         'Decomposer Algid Hybrid Administrations Unit III Blueprint', 'Warhead Flare Catalyst I Blueprint',
         'Warhead Flare Catalyst II Blueprint', 'Warhead Flare Catalyst III Blueprint',
         'Warhead Calefaction Catalyst I Blueprint', 'Warhead Calefaction Catalyst II Blueprint',
         'Warhead Calefaction Catalyst III Blueprint', 'Warhead Rigor Catalyst I Blueprint',
         'Warhead Rigor Catalyst II Blueprint', 'Warhead Rigor Catalyst III Blueprint',
         'Rocket Fuel Cache Partition I Blueprint', 'Rocket Fuel Cache Partition II Blueprint',
         'Rocket Fuel Cache Partition III Blueprint', 'Hydraulic Bay Thrusters I Blueprint',
         'Hydraulic Bay Thrusters II Blueprint', 'Hydraulic Bay Thrusters III Blueprint',
         'Bay Loading Accelerator I Blueprint', 'Bay Loading Accelerator II Blueprint',
         'Bay Loading Accelerator III Blueprint', 'Core Defense Operational Solidifier I Blueprint',
         'Core Defense Operational Solidifier II Blueprint', 'Core Defense Operational Solidifier III Blueprint',
         'Core Defense Charge Economizer I Blueprint', 'Core Defense Charge Economizer II Blueprint',
         'Core Defense Charge Economizer III Blueprint', 'Core Defense Capacitor Safeguard I Blueprint',
         'Core Defense Capacitor Safeguard II Blueprint', 'Core Defense Capacitor Safeguard III Blueprint',
         'Core Defense Field Extender I Blueprint', 'Core Defense Field Extender II Blueprint',
         'Core Defense Field Extender III Blueprint', 'Small Anti-Explosive Screen Reinforcer I Blueprint',
         'Small Anti-Explosive Screen Reinforcer II Blueprint',
         'Small Anti-Explosive Screen Reinforcer III Blueprint',
         'Anti-EM Screen Reinforcer I Blueprint', 'Anti-EM Screen Reinforcer II Blueprint',
         'Anti-EM Screen Reinforcer III Blueprint', 'Anti-Kinetic Screen Reinforcer I Blueprint',
         'Anti-Kinetic Screen Reinforcer II Blueprint', 'Anti-Kinetic Screen Reinforcer III Blueprint',
         'Anti-Thermal Screen Reinforcer I Blueprint', 'Anti-Thermal Screen Reinforcer II Blueprint',
         'Anti-Thermal Screen Reinforcer III Blueprint', 'Nanobot Accelerator I Blueprint',
         'Nanobot Accelerator II Blueprint', 'Nanobot Accelerator III Blueprint', 'Auxiliary Nano Pump I Blueprint',
         'Auxiliary Nano Pump II Blueprint', 'Auxiliary Nano Pump III Blueprint',
         'Remote Repair Augmentor I Blueprint',
         'Remote Repair Augmentor II Blueprint', 'Remote Repair Augmentor III Blueprint',
         'Small Trimark Armor Pump I Blueprint', 'Small Trimark Armor Pump II Blueprint',
         'Small Trimark Armor Pump III Blueprint', 'Small Anti-Explosive Pump I Blueprint',
         'Small Anti-Explosive Pump II Blueprint', 'Small Anti-Explosive Pump III Blueprint',
         'Small Anti-EM Pump I Blueprint', 'Small Anti-EM Pump II Blueprint', 'Small Anti-EM Pump III Blueprint',
         'Small Anti-Kinetic Pump I Blueprint', 'Small Anti-Kinetic Pump II Blueprint',
         'Small Anti-Kinetic Pump III Blueprint', 'Small Anti-Thermal Pump I Blueprint',
         'Small Anti-Thermal Pump II Blueprint', 'Small Anti-Thermal Pump III Blueprint',
         'Small Dynamic Fuel Valve I Blueprint', 'Small Dynamic Fuel Valve II Blueprint',
         'Small Dynamic Fuel Valve III Blueprint', 'Auxiliary Thrusters I Blueprint',
         'Auxiliary Thrusters II Blueprint', 'Auxiliary Thrusters III Blueprint',
         'Small Polycarbon Engine Housing I Blueprint', 'Small Polycarbon Engine Housing II Blueprint',
         'Small Polycarbon Engine Housing III Blueprint', 'Cargohold Optimization I Blueprint',
         'Cargohold Optimization II Blueprint', 'Cargohold Optimization III Blueprint', 'Higgs Anchor I Blueprint',
         'Higgs Anchor II Blueprint', 'Higgs Anchor III Blueprint', 'Warp Core Optimizer I Blueprint',
         'Warp Core Optimizer II Blueprint', 'Warp Core Optimizer III Blueprint',
         'Hyperspatial Velocity Optimizer I Blueprint', 'Hyperspatial Velocity Optimizer II Blueprint',
         'Hyperspatial Velocity Optimizer III Blueprint', 'Small Semiconductor Memory Cell I Blueprint',
         'Small Semiconductor Memory Cell II Blueprint', 'Small Semiconductor Memory Cell III Blueprint',
         'Capacitor Control Circuit I Blueprint', 'Capacitor Control Circuit II Blueprint',
         'Capacitor Control Circuit III Blueprint', 'Ancillary Powergrid Router I Blueprint',
         'Ancillary Powergrid Router II Blueprint', 'Ancillary Powergrid Router III Blueprint',
         'Targeting System Subcontroller I Blueprint', 'Targeting System Subcontroller II Blueprint',
         'Targeting System Subcontroller III Blueprint', 'Gravity Capacitor Upgrade I Blueprint',
         'Gravity Capacitor Upgrade II Blueprint', 'Gravity Capacitor Upgrade III Blueprint',
         'Emission Scope Sharpener I Blueprint', 'Emission Scope Sharpener II Blueprint',
         'Emission Scope Sharpener III Blueprint', 'Miner Efficiency Upgrade I Blueprint',
         'Miner Efficiency Upgrade II Blueprint', 'Miner Efficiency Upgrade III Blueprint',
         'Miner Circulation Accelerator I Blueprint', 'Miner Circulation Accelerator II Blueprint',
         'Miner Circulation Accelerator III Blueprint', 'Miner Range Controller I Blueprint',
         'Miner Range Controller II Blueprint', 'Miner Range Controller III Blueprint',
         'Miner Algid Optimizer I Blueprint', 'Miner Algid Optimizer II Blueprint',
         'Miner Algid Optimizer III Blueprint', 'Transverse Bulkhead I Blueprint',
         'Transverse Bulkhead II Blueprint',
         'Transverse Bulkhead III Blueprint', 'Anti-Explosive Transverse Bulkhead I Blueprint',
         'Anti-Explosive Transverse Bulkhead II Blueprint', 'Anti-Explosive Transverse Bulkhead III Blueprint',
         'Anti-EM Transverse Bulkhead I Blueprint', 'Anti-EM Transverse Bulkhead II Blueprint',
         'Anti-EM Transverse Bulkhead III Blueprint', 'Anti-Kinetic Transverse Bulkhead I Blueprint Blueprint',
         'Anti-Kinetic Transverse Bulkhead II Blueprint', 'Anti-Kinetic Transverse Bulkhead III Blueprint',
         'Anti-Thermal Transverse Bulkhead I Blueprint', 'Anti-Thermal Transverse Bulkhead II Blueprint',
         'Anti-Thermal Transverse Bulkhead III Blueprint', 'Sentry Damage Augmentor I Blueprint',
         'Sentry Damage Augmentor II Blueprint', 'Sentry Damage Augmentor III Blueprint',
         'Drone Scope Chip I Blueprint', 'Drone Scope Chip II Blueprint', 'Drone Scope Chip III Blueprint',
         'Drone Speed Augmentor I Blueprint', 'Drone Speed Augmentor II Blueprint',
         'Drone Speed Augmentor III Blueprint', 'Drone Control Range Augmentor I Blueprint',
         'Drone Control Range Augmentor II Blueprint', 'Drone Control Range Augmentor III Blueprint',
         'MK3 Acolyte Blueprint', 'MK5 Acolyte Blueprint', 'MK7 Acolyte Blueprint', 'MK9 Acolyte Blueprint',
         'MK3 Hornet Blueprint', 'MK5 Hornet Blueprint', 'MK7 Hornet Blueprint', 'MK3 Hobgoblin Blueprint',
         'MK5 Hobgoblin Blueprint', 'MK7 Hobgoblin Blueprint', 'MK9 Hobgoblin Blueprint', 'MK3 Warrior Blueprint',
         'MK5 Warrior Blueprint', 'MK7 Warrior Blueprint', 'MK9 Warrior Blueprint', 'MK5 Infiltrator Blueprint',
         'MK7 Infiltrator Blueprint', 'MK9 Infiltrator Blueprint', 'MK5 Vespa Blueprint', 'MK7 Vespa Blueprint',
         'MK9 Vespa Blueprint', 'MK5 Hammerhead Blueprint', 'MK7 Hammerhead Blueprint', 'MK9 Hammerhead Blueprint',
         'MK5 Valkyrie Blueprint', 'MK7 Valkyrie Blueprint', 'MK9 Valkyrie Blueprint', 'MK7 Praetor Blueprint',
         'MK9 Praetor Blueprint', 'MK7 Wasp Blueprint', 'MK9 Wasp Blueprint', 'MK7 Ogre Blueprint',
         'MK9 Ogre Blueprint', 'MK7 Berserker Blueprint', 'MK9 Berserker Blueprint', 'MK7 Curator Blueprint',
         'MK9 Curator Blueprint', 'MK7 Warden Blueprint', 'MK9 Warden Blueprint', 'MK7 Guard Blueprint',
         'MK9 Guard Blueprint', 'MK7 Bouncer Blueprint', 'MK9 Bouncer Blueprint', 'Capsuleer Outpost Blueprint',
         'Standard Standup Small Missile Launcher Blueprint', 'Standard Standup Medium Missile Launcher Blueprint',
         'Standard Standup Large Missile Launcher Blueprint', 'Standard Standup Stasis Webifier Blueprint',
         'Standard Standup Warp Disruptor Blueprint', 'Standard Standup Energy Neutralizer Blueprint',
         'Industry Service Center Blueprint', 'Structure Construction Parts Blueprint',
         'Structure Hangar Array Blueprint', 'Structure Storage Bay Blueprint', 'Structure Laboratory Blueprint',
         'Structure Factory Blueprint', 'Structure Repair Facility Blueprint',
         'Structure Reprocessing Plant Blueprint',
         'Structure Docking Bay Blueprint', 'Structure Market Network Blueprint',
         'Structure Medical Center Blueprint',
         'Structure Office Center Blueprint', 'Structure Mission Network Blueprint',
         'Structure Electromagnetic Sensor Blueprint', 'Structure Acceleration Coils Blueprint',
         'Structure Advertisement Nexus Blueprint', 'Impairor White blade SKIN(permanent)',
         'Impairor Jagged SKIN(permanent)', 'Ibis Ghost Bird SKIN(permanent)', 'Ibis Marty Kraken SKIN(permanent)',
         'Velator Edge of Edge SKIN(permanent)', 'Velator Short-distance Delivery SKIN(permanent)',
         'Reaper Glory of Vakir SKIN(permanent)', 'Reaper Nefantar SKIN(permanent)',
         'Venture Trainer Mining Masters Emblem SKIN(permanent)', 'Venture Mining Masters Emblem SKIN(permanent)',
         'Retriever Mining Masters Emblem SKIN(permanent)', 'Venture Trainer Wealth Explorer SKIN(permanent)',
         'Venture Wealth Explorer SKIN(permanent)', 'Retriever Wealth Explorer SKIN(permanent)',
         'Procurer Wealth Explorer SKIN(permanent)', 'Porpoise Wealth Explorer SKIN(permanent)',
         'Covetor Wealth Explorer SKIN(permanent)', 'Tormentor Alien Hunter SKIN(permanent)',
         'Magnate Alien Hunter SKIN(permanent)', 'Punisher Alien Hunter SKIN(permanent)',
         'Coercer Alien Hunter SKIN(permanent)', 'Dragoon Alien Hunter SKIN(permanent)',
         'Dragoon Trainer Alien Hunter SKIN(permanent)', 'Omen Alien Hunter SKIN(permanent)',
         'Omen Trainer Alien Hunter SKIN(permanent)', 'Maller Alien Hunter SKIN(permanent)',
         'Arbitrator Alien Hunter SKIN(permanent)', 'Maller Trainer Alien Hunter SKIN(permanent)',
         'Merlin Alien Hunter SKIN(permanent)', 'Kestrel Alien Hunter SKIN(permanent)',
         'Heron Alien Hunter SKIN(permanent)', 'Cormorant Alien Hunter SKIN(permanent)',
         'Corax Alien Hunter SKIN(permanent)', 'Corax Trainer Alien Hunter SKIN(permanent)',
         'Caracal Alien Hunter SKIN(permanent)', 'Caracal Trainer Alien Hunter SKIN(permanent)',
         'Moa Alien Hunter SKIN(permanent)', 'Blackbird Alien Hunter SKIN(permanent)',
         'Moa Trainer Alien Hunter SKIN(permanent)', 'Tristan Alien Hunter SKIN(permanent)',
         'Incursus Alien Hunter SKIN(permanent)', 'Imicus Alien Hunter SKIN(permanent)',
         'Catalyst Alien Hunter SKIN(permanent)', 'Algos Alien Hunter SKIN(permanent)',
         'Algos Trainer Alien Hunter SKIN(permanent)', 'Vexor Alien Hunter SKIN(permanent)',
         'Vexor Trainer Alien Hunter SKIN(permanent)', 'Thorax Alien Hunter SKIN(permanent)',
         'Celestis Alien Hunter SKIN(permanent)', 'Thorax Trainer Alien Hunter SKIN(permanent)',
         'Rifter Alien Hunter SKIN(permanent)', 'Probe Alien Hunter SKIN(permanent)',
         'Thrasher Alien Hunter SKIN(permanent)', 'Talwar Alien Hunter SKIN(permanent)',
         'Talwar Trainer Alien Hunter SKIN(permanent)', 'Stabber Alien Hunter SKIN(permanent)',
         'Stabber Trainer Alien Hunter SKIN(permanent)', 'Rupture Trainer Alien Hunter SKIN(permanent)',
         'Tormentor Holy Throne SKIN(permanent)', 'Magnate Holy Throne SKIN(permanent)',
         'Punisher Holy Throne SKIN(permanent)', 'Coercer Holy Throne SKIN(permanent)',
         'Dragoon Holy Throne SKIN(permanent)', 'Dragoon Trainer Holy Throne SKIN(permanent)',
         'Omen Holy Throne SKIN(permanent)', 'Omen Trainer Holy Throne SKIN(permanent)',
         'Maller Holy Throne SKIN(permanent)', 'Arbitrator Holy Throne SKIN(permanent)',
         'Maller Trainer Holy Throne SKIN(permanent)', 'Merlin Holy Throne SKIN(permanent)',
         'Kestrel Holy Throne SKIN(permanent)', 'Heron Holy Throne SKIN(permanent)',
         'Cormorant Holy Throne SKIN(permanent)', 'Corax Holy Throne SKIN(permanent)',
         'Corax Trainer Holy Throne SKIN(permanent)', 'Caracal Holy Throne SKIN(permanent)',
         'Caracal Trainer Holy Throne SKIN(permanent)', 'Moa Holy Throne SKIN(permanent)',
         'Blackbird Holy Throne SKIN(permanent)', 'Moa Trainer Holy Throne SKIN(permanent)',
         'Tristan Holy Throne SKIN(permanent)', 'Incursus Holy Throne SKIN(permanent)',
         'Imicus Holy Throne SKIN(permanent)', 'Catalyst Holy Throne SKIN(permanent)',
         'Algos Holy Throne SKIN(permanent)', 'Algos Trainer Holy Throne SKIN(permanent)',
         'Vexor Holy Throne SKIN(permanent)', 'Vexor Trainer Holy Throne SKIN(permanent)',
         'Thorax Holy Throne SKIN(permanent)', 'Celestis Holy Throne SKIN(permanent)',
         'Thorax Trainer Holy Throne SKIN(permanent)', 'Rifter Holy Throne SKIN(permanent)',
         'Probe Holy Throne SKIN(permanent)', 'Thrasher Holy Throne SKIN(permanent)',
         'Talwar Holy Throne SKIN(permanent)', 'Talwar Trainer Holy Throne SKIN(permanent)',
         'Stabber Holy Throne SKIN(permanent)', 'Stabber Trainer Holy Throne SKIN(permanent)',
         'Bellicose Holy Throne SKIN(permanent)', 'Rupture Trainer Holy Throne SKIN(permanent)',
         'Executioner Red copper SKIN(permanent)', 'Coercer Red copper SKIN(permanent)',
         'Omen Red copper SKIN(permanent)', 'Omen Trainer Red copper SKIN(permanent)',
         'Prophecy Red copper SKIN(permanent)', 'Apocalypse Red copper SKIN(permanent)',
         'Atron Titanium silver SKIN(permanent)', 'Catalyst Titanium silver SKIN(permanent)',
         'Vexor Titanium silver SKIN(permanent)', 'Vexor Trainer Titanium silver SKIN(permanent)',
         'Myrmidon Titanium silver SKIN(permanent)', 'Megathron Titanium silver SKIN(permanent)',
         'Condor Ochre SKIN(permanent)', 'Cormorant Ochre SKIN(permanent)', 'Caracal Ochre SKIN(permanent)',
         'Ferox Ochre SKIN(permanent)', 'Rokh Ochre SKIN(permanent)', 'Slasher Soot SKIN(permanent)',
         'Thrasher Soot SKIN(permanent)', 'Stabber Soot SKIN(permanent)', 'Cyclone Soot SKIN(permanent)',
         'Xian-Yue Prototype Lunar Eclipse SKIN(permanent)', 'Xian-Yue Lunar Eclipse SKIN(permanent)',
         'Coercer Earth  SKIN(permanent)', 'Cormorant Earth  SKIN(permanent)', 'Catalyst Earth  SKIN(permanent)',
         'Thrasher Earth  SKIN(permanent)', 'Maller Earth  SKIN(permanent)', 'Moa Earth  SKIN(permanent)',
         'Rupture Earth  SKIN(permanent)', 'Maller Trainer Earth  SKIN(permanent)',
         'Moa Trainer Earth  SKIN(permanent)', 'Corax Gas  SKIN(permanent)', 'Algos Gas  SKIN(permanent)',
         'Talwar Gas  SKIN(permanent)', 'Dragoon Trainer Gas  SKIN(permanent)',
         'Corax Trainer Gas  SKIN(permanent)',
         'Algos Trainer Gas  SKIN(permanent)', 'Talwar Trainer Gas  SKIN(permanent)', 'Prophecy Gas  SKIN(15 days)',
         'Myrmidon Gas  SKIN(permanent)', 'Cyclone Gas  SKIN(permanent)', 'Drake Gas  SKIN(permanent)',
         'Purifier Fire  SKIN(permanent)', 'Manticore Fire  SKIN(permanent)', 'Nemesis Fire  SKIN(permanent)',
         'Hound Fire  SKIN(permanent)', 'Scorpion Fire  SKIN(permanent)', 'Typhoon Fire  SKIN(permanent)',
         'Merlin Water  SKIN(permanent)', 'Rifter Water  SKIN(permanent)', 'Punisher Water  SKIN(permanent)',
         'Incursus Water  SKIN(permanent)', 'Omen Water  SKIN(permanent)', 'Omen Trainer Water  SKIN(permanent)',
         'Moa Water  SKIN(permanent)', 'Thorax Water  SKIN(permanent)', 'Rupture Water  SKIN(permanent)']
intents = discord.Intents.default()

client = discord.Client(intent=intents)


def for_data(data):
    new_data = {}

    bp = data["buy"]
    if bp == None:
        bp = -1
    else:
        bp = int(bp)
    if bp > 1000000:
        new_data["buy"] = str((bp / 1000000).__round__(5)) + " M ISK"
    elif bp > 0:
        new_data["buy"] = str(bp) + " ISK"
    else:
        new_data["buy"] = "N.A."

    sp = data["sell"]
    if sp == None:
        sp = -1
    else:
        sp = int(sp)
    if sp > 1000000:
        new_data["sell"] = str((sp / 1000000).__round__(2)) + " M ISK"
    elif sp > 0:
        new_data["sell"] = str(sp) + " ISK"
    else:
        new_data["sell"] = "N.A."
    return new_data


@client.event
async def on_ready():
    print("Ready")


@client.event
async def on_message(message):
    if message.author.bot or message.author.id == 764723144966668299 or message.channel.id != 764724045420822578:
        return
    if "!g" not in message.content:
        return
    nameofitem = message.content[3:]
    print(nameofitem)
    if nameofitem not in names:
        nameofitems = process.extract(nameofitem, names)
        nameofitem = nameofitems[0][0]
        print(nameofitems)
    path, data = getimage(nameofitem)
    data = for_data(data)
    print(data)
    print("Path=", path)
    await message.channel.send("Sell Price : {}\nBuy Price : {}".format(data["sell"], data["buy"]),
                               file=discord.File(path))
    try:
        os.remove("images/{}.png".format(nameofitem))
    except:
        pass


client.run("token")
